### ISSUE TITLE
Create simple CLI interface which print CLI arguments

### ISSUE THREAD

**Issue by nesterone** [Jaspersoft/faf-build-metrics-importer#2]
https://github.com/Jaspersoft/faf-build-metrics-importer/blob/master/main.js

**Comment by nesterone** [comment]
To dev branch
from @zigfred  a list of CLI argumets (names and descriptions)

**Comment by zigfred** [comment]
CLI arguments:

job_name - text (module-jrs-ui-pro-trunk-jade-new-css-html)
build - number (35)
started - timestamp (1447938126624)
started_by - text (user name)
result - text (SUCCESS UNSTABLE FAILURE)
change_set ???
